name: Run News Scraper (Google & Yahoo)

on:
  schedule:
    # JST 9:00 -> UTC 0:00
    - cron: '0 0 * * *'
    # JST 10:00 -> UTC 1:00
    - cron: '0 1 * * *'
    # JST 10:10 -> UTC 1:10
    - cron: '10 1 * * *'
    # JST 10:20 -> UTC 1:20
    - cron: '20 1 * * *'
    # JST 10:30 -> UTC 1:30
    - cron: '30 1 * * *'
    # JST 10:40 -> UTC 1:40
    - cron: '40 1 * * *'
    # JST 10:50 -> UTC 1:50
    - cron: '50 1 * * *'
    # JST 11:00 -> UTC 2:00
    - cron: '0 2 * * *'
    # JST 12:00 -> UTC 3:00
    - cron: '0 3 * * *'

  workflow_dispatch:

jobs:
  scrape-news:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Scraper
      env:
      # ここでシークレットを環境変数にマッピング
        YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
        GCP_SERVICE_ACCOUNT_KEY: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
      run: |
        python main.py

    - name: Check for workflow failure (optional)
      if: ${{ failure() }}
      run: echo "Workflow failed. Check logs for details."
